// codes from https://www.nalc.org/workplace-issues/resources/manuals/PO-610-November-2014.pdf
// and https://github.com/hautelook/shipment-tracking/blob/d326529d243bbefe8c712d8e8b573757170f0a5a/src/Provider/USPS/EventCode.php
// and https://mailomg.files.wordpress.com/2018/09/ptr-domestic-scan-events-and-descriptions.pdf
// and https://shipping.pitneybowes.com/reference/scan-events.html
// and https://about.usps.com/publications/pub97/pub97_appi.htm

import PackageStatus from '../../package/PackageStatus';

const DELIVERED = '01';
const NOTICE_LEFT = '02'; // Accompanied by subset events 53-56
const ACCEPT_OR_PICKUP = '03';
const REFUSED = '04';
const UNDELIVERABLE_AS_ADDRESSED = '05';
const FORWARDED = '06';
const ARRIVAL_AT_UNIT = '07';
const MISSENT = '08';
const RETURN_TO_SENDER_1 = '09'; // Accompanied by subset events 21-27
const PROCESSED = '10';
const SEIZED_BY_LAW_ENFORCEMENT = '11';
const VISIBLE_DAMAGE = '12';
const AUTHORIZED_AGENT = '13';
const AVAILABLE_FOR_PICKUP_IN_OFFICE = '14'; // In-office user only
const MIS_SHIPPED = '15';
const AVAILABLE_FOR_PICKUP = '16';
const PICKED_UP_BY_AGENT = '17';
const RANDOM_SAMPLING = '18';
const DC_EVS_ARRIVE = '19';
const NO_SUCH_NUMBER = '21'; // Subset of event 09
const INSUFFICIENT_ADDRESS = '22'; // Subset of event 09
const MOVED_LEFT_NO_ADDRESS = '23'; // Subset of event 09
const FORWARD_EXPIRED = '24'; // Subset of event 09
const ADDRESSEE_UNKNOWN = '25'; // Subset of event 09
const VACANT = '26'; // Subset of event 09
const UNCLAIMED = '27'; // Subset of event 09
const RETURN_TO_SENDER_2 = '28';
const RETURN_TO_SENDER_3 = '29';
const NO_ACCESS = '30';
const RETURN_TO_SENDER_NOT_PICKED_UP = '31';
const DEAD_MAIL_DISPOSED_BY_POST_OFFICE = '32';
const DEAD_MAIL_SENT_TO_RECOVERY_CENTER = '33';
const TRANSFER_TO_VAULT = '34';
const VAULT_TURNOVER = '35';
const TRANSFER_TO_EMPLOYEE = '36';
const REGISTERED_MAIL_DISPATCH_SIGNATURE = '38';
const REGISTERED_MAIL_DISPATCH_WITNESS = '39';
const TRANSFER_FROM_VAULT = '40';
const RECEIVED_AT_OPENING_UNIT = '41';
const USPS_HAND_OFF_TO_SHIPPING_PARTNER = '42';
const PICKED_UP = '43';
const PACKAGE_INTERCEPT = '44';
const DISPATCHED_TO_MILITARY = '45';
const DUPLICATE_LABEL_ID = '46';
const BUSINESS_CLOSED = '51';
const TEMPORARY_VACATION_HOLD = '52';
const RECEPTACLE_BLOCKED = '53'; // Subset of event 02
const RECEPTACLE_FULL_ITEM_OVERSIZED = '54'; // Subset of event 02
const NO_SECURE_LOCATION_AVAILABLE = '55'; // Subset of event 02
const NO_AUTHORIZED_RECIPIENT_AVAILABLE = '56'; // Subset of event 02
const HAZARDOUS_UNSAFE_DELIVERY_CONDITIONS = '57';
const HELD_AT_POST_OFFICE_AT_CUSTOMER_REQUEST = '58';
const OUT_FOR_DELIVERY_ON_STREET = '59';
const TENDERED_TO_AGENT_FINAL_DELIVERY = '60';
const RECEIVED_BY_AGENT = '61';
const RECIPIENT_NOTIFIED_BY_AGENT = '62';
const DELIVERED_TO_RECIPIENT_BY_AGENT = '63';
const UNDELIVERABLE_TO_RECIPIENT_BY_AGENT = '64';
const RESCHEDULED_TO_NEXT_DELIVERY_DAY = '71';
const DELIVERY_EXCEPTION_ANIMAL_INTERFERENCE = '72';
const PICKED_UP_BY_SHIPPING_PARTNER = '80';
const ARRIVED_SHIPPING_PARTNER_FACILITY = '81';
const DEPARTED_SHIPPING_PARTNER_FACILITY = '82';
const TENDERED_TO_POSTAL_SERVICE = '83';
const ARRIVED_AT_AGENT_FACILITY = '84';
const DEPART_AGENT_FACILITY = '85';
const DELIVERED_BY_AGENT_TO_MERCHANT = '86';
const FINAL_DISPOSITION_BY_AGENT = '87';
const FOREIGN_ACCEPTANCE = 'A0';
const TRAILER_ARRIVE = 'A1';
const ACEPTANCE_AT_DESTINATION = 'AD';
const ARRIVE_USPS_SORT_FACILITY = 'AE';
const HANDOFF_INTERMEDIATE_CARRIER = 'AF';
const RECEIVED_FROM_INTERMEDIATE_CARRIER = 'AG';
const DELIVERED_TO_POSTAL_AGENT = 'AH';
const INTERMEDIATE_TRANSFER_AIRPORT = 'AJ';
const ACCEPTED_BY_ORIGIN_CARRIER = 'AP';
const INBOUND_INTERNATIONAL_ARRIVAL = 'AR';
const ARRIVED_IN_DESTINATION_COUNTRY = 'AS';
const ORIGIN_CARRIER_DEPARTED_UPLIFT = 'AT';
const FOREIGN_ARRIVAL_AT_OUTWARD_OFFICE = 'B0';
const OUTBOUND_INTO_US_CUSTOMS = 'B1';
const INTO_CUSTOMS = 'B2';
const OUT_OF_CUSTOMS = 'B3';
const OUTBOUND_OUT_OF_US_CUSTOMS = 'B5';
const BAD_ADDRESS = 'BA';
const ENTERED_AT_PLANT = 'BB';
const PROCESSED_2 = 'BE';
const DELIVERED_BY_BROKER = 'BR';
const BUMPED_DELAY = 'BX';
const FOREIGN_INTERNATIONAL_DISPATCH = 'C0';
const CONTAINER_CLOSE = 'C1';
const CLOSED_ON_ARRIVAL = 'CA';
const AWAITING_CONSIGNEE_COLLECTION = 'CC';
const CLEARANCE_DELAY = 'CD';
const INBOUND_INTO_CUSTOMS = 'CI';
const CUSTOMER_MOVED = 'CM';
const INBOUND_OUT_OF_CUSTOMS = 'CO';
const RELEASE_FROM_CUSTOMS_BOND = 'CR';
const HELD_AT_INWARD_OFFICE_OF_EXCHANGE = 'DA'; // Foreign event
const ARRIVED_ABROAD = 'D0'; // Foreign event
const ITEM_INTO_SORTING_CENTER = 'D1'; // Foreign event
const ITEM_OUT_OF_SORTING_CENTER = 'D2'; // Foreign event
const DISTRIBUTION_COMPLETE = 'DC';
const INTERNATIONAL_DISPATCH_READY = 'DD';
const DEPART_USPS_SORT_FACILITY = 'DE';
const ITEM_HELD_AT_DELIVERY_DEPOT = 'DF'; // Foreign event
const ITEM_OUT_FOR_DELIVERY = 'DG'; // Foreign event
const ITEM_ARRIVAL_AT_COLLECTION_POINT_FOR_PICKUP = 'DH'; // Foreign event
const DELIVERED_WITH_SIGNATURE = 'DL';
const DELIVERED_DAMAGED = 'DN';
const DISPOSAL = 'DP';
const TRANSIT_MAIL_DISPATCH = 'DT';
const DELIVERY_STATUS_NOT_UPDATED = 'DX';
const INTO_FOREIGN_CUSTOMS = 'E0';
const DEPARTED = 'E1';
const ENROUTE_ARRIVAL_INWARD = 'EA';
const ENROUTE_ARRIVAL_OUTWARD = 'EB';
const ENROUTE_DEPARTURE = 'ED';
const DISPATCHED_FROM_SORT_FACILITY = 'EF';
const OUT_OF_FOREIGN_CUSTOMS = 'F0';
const WITH_DELIVERY_COURIER = 'FD';
const AT_FOREIGN_DELIVERY_UNIT = 'G0';
const RETURN_RECEIPT_ASSOCIATED = 'GC';
const PREPARED_FOR_AGENT = 'GX';
const ATTEMPTED_DELIVERY_ABROAD = 'H0';
const FOREIGN_RETURN_TO_SENDER = 'H8';
const HELD_FOR_PAYMENT = 'HP';
const HOLIDAY_DELAY = 'HX';
const DELIVERED_ABROAD = 'I0';
const RECEIPT_INTO_CUSTOMS_BOND = 'IC';
const IMPORT_CANCELLATION = 'IX'; // Foreign event
const ARRIVAL_AT_TRANSIT_OFFICE_FROM_OF_EXCHANGE = 'J0';
const DEPART_FROM_TRANSIT_OFFICE_OF_EXCHANGE = 'K0';
const FORWARDING_TO_US_CUSTOMS = 'K1';
const CONTACT_US_CUSTOMS = 'K2';
const FORWARDED_BY_USPS = 'K3';
const RTS_IMPROPER_DOCUMENTATION = 'K4';
const RTS_ABANDONMENT = 'K5';
const RTS_DUTY_NONPAYMENT = 'K6';
const PICKED_UP_AT_CUSTOMS_UNIT = 'K7';
const CONTAINER_LOAD = 'L1';
const ARRIVAL_AT_DESTINATION_ADDRESS = 'LD';
const MISSED_DELIVERY_CYCLE = 'LT';
const LOOP_MAIL_EXCEPTION = 'LX';
const ELECTRONIC_SHIPPING_INFO_RECEIVED = 'MA'; // Manifest Acknowledgement
const MISCODE = 'MC';
const HELD_BY_IMPORT_CUSTOMS = 'ME'; // Foreign event
const ITEM_DEPARTED_FROM_DESTINATION_OFFICE_OF_EXCHANGE = 'MF'; // Foreign event
const PICKED_UP_AND_PROCESSED_BY_AGENT = 'MR';
const MISSORT = 'MS';
const MISSENT_ZIP_NOT_CHANGED_PMPC_SCAN = 'MT';
const ALERT_MID_USER_NEEDS_TO_BE_REGISTERED = 'MU';
const ALERT_UNAUTHORIZED_MID_USE = 'MX';
const MISSENT_ZIP_CHANGED_PMPC_SCAN = 'MZ';
const NOT_DELIVERED = 'ND';
const NOT_HOME = 'NH';
const ORIGIN_POST_IS_PREPARING_SHIPMENT = 'NP';
const ORIGIN_ACCEPTANCE = 'OA';
const OUTBOUND_PRECON = 'OC'; // Planned only
const PROCESSED_AT_DESTINATION_FACILITY = 'OD';
const OUT_FOR_DELIVERY = 'OF';
const ON_HOLD = 'OH';
const INTERNATIONAL_DELIVERED_WITH_SIGNATURE = 'OK';
const ON_SERVICE = 'ON';
const OUTBOUND_PREDES = 'OP'; // Planned only
const OUTBOUND_RESDIT = 'OR'; // Planned only
const OUTBOUND_RESDES = 'OS'; // Planned only
const PROCESSING_EXCEPTION_OTHER_DELAY = 'OX';
const BULK_ENROUTE_ACCEPTANCE = 'PA'; // Passive Acceptance
const SORTING_PROCESSING_COMPLETE = 'PC';
const PARTIAL_DELIVERY = 'PD';
const EPG_ORIGIN_POST_IS_PREPARING_SHIPMENT = 'PE';
const INBOUND_PRECON = 'PN'; // Planned only
const PROCESSED_AT_ORIGIN = 'PO';
const PROHIBITED = 'PR';
const SHIPMENT_PICK_UP = 'PU';
const READY_TO_PROCESS = 'R1';
const LISTED_ON_REGISTERED_MAIL_DISPATCH_BILL = 'RB';
const DISPATCH_FORM_DISCREPANCY = 'RC';
const REFUSED_DELIVERY = 'RD';
const REFUSED_ENTRY_BY_CUSTOMS = 'RE';
const RETURNED_TO_CONSIGNOR = 'RT';
const SERVICE_CHANGE = 'SC';
const DISPATCHED_TO_SORT_FACILITY = 'SF';
const SHIPMENT_STOPPED = 'SS';
const TRAILER_DEPART = 'T1';
const TRANSIT_MAIL_ARRIVAL = 'TA';
const SHIPMENT_ACCEPTANCE = 'TM'; // Truck Manifest
const ONFORWARDED_TO_THIRD_PARTY = 'TP';
const TRANSFERRED_THROUGH_SERVICE_CENTER = 'TR';
const TRANSIT = 'TS';
const PROCESSING_EXCEPTION_REG_TRANS_DELAY = 'TX';
const TRAILER_UNLOAD = 'U1';
const UNMANIFESTED_ACCEPTANCE = 'UA';
const DC_EVS_ARRIVE_VERIFICATION_ACCEPTANCE = 'VA';
const PACKAGE_RESEARCH_CASE_CREATED = 'VC';
const SECOND_NOTICE_GENERATED = 'VF';
const DELIVERY_INSTRUCTION_REQUEST_FAILURE = 'VH';
const DELIVERY_INSTRUCTION_UNFULFILLED = 'VJ';
const CARRIER_PICK_UP = 'VP';
const REDELIVERY_SCHEDULED = 'VR';
const PACKAGE_RETURN_NOTICE_GENERATED = 'VS';
const PACKAGE_RESEARCH_ASE_CLOSED = 'VX';
const WITH_COURIER = 'WC';
const WEATHER_DELAY = 'WX';
const ITEM_PRESENTED_TO_EXPORT_CUSTOMS = 'XA'; // Foreign event
const ITEM_HELD_BY_EXPORT_CUSTOMS = 'XB'; // Foreign event
const ITEM_RETURNED_FROM_CUSTOMS = 'XC'; // Foreign event
const ITEM_HELD_AT_OUTWARD_OFFICE_OF_EXCHANGE = 'XD'; // Foreign event
const EXPORT_CANCELATION = 'XX'; // Foreign event

export default new Map<string, PackageStatus>([
    [DELIVERED, PackageStatus.DELIVERED],
    [DELIVERED_ABROAD, PackageStatus.DELIVERED],
    [DELIVERED_BY_BROKER, PackageStatus.DELIVERED],
    [DELIVERED_DAMAGED, PackageStatus.DELIVERED],
    [DELIVERED_TO_POSTAL_AGENT, PackageStatus.DELIVERED],
    [DELIVERED_WITH_SIGNATURE, PackageStatus.DELIVERED],
    [INTERNATIONAL_DELIVERED_WITH_SIGNATURE, PackageStatus.DELIVERED],
    [TENDERED_TO_AGENT_FINAL_DELIVERY, PackageStatus.DELIVERED],
    [PICKED_UP_BY_AGENT, PackageStatus.DELIVERED],

    [RETURN_TO_SENDER_1, PackageStatus.RETURNED_TO_SENDER],
    [RETURN_TO_SENDER_2, PackageStatus.RETURNED_TO_SENDER],
    [RETURN_TO_SENDER_3, PackageStatus.RETURNED_TO_SENDER],
    [RETURN_TO_SENDER_NOT_PICKED_UP, PackageStatus.RETURNED_TO_SENDER],
    [FOREIGN_RETURN_TO_SENDER, PackageStatus.RETURNED_TO_SENDER],
    [REFUSED, PackageStatus.RETURNED_TO_SENDER],
    [REFUSED_DELIVERY, PackageStatus.RETURNED_TO_SENDER],
    [REFUSED_ENTRY_BY_CUSTOMS, PackageStatus.RETURNED_TO_SENDER],
    [UNDELIVERABLE_AS_ADDRESSED, PackageStatus.RETURNED_TO_SENDER],
    [NO_SUCH_NUMBER, PackageStatus.RETURNED_TO_SENDER],
    [INSUFFICIENT_ADDRESS, PackageStatus.RETURNED_TO_SENDER],
    [MOVED_LEFT_NO_ADDRESS, PackageStatus.RETURNED_TO_SENDER],
    [FORWARD_EXPIRED, PackageStatus.RETURNED_TO_SENDER],
    [ADDRESSEE_UNKNOWN, PackageStatus.RETURNED_TO_SENDER],
    [VACANT, PackageStatus.RETURNED_TO_SENDER],
    [UNCLAIMED, PackageStatus.RETURNED_TO_SENDER],
    [BAD_ADDRESS, PackageStatus.RETURNED_TO_SENDER],
    [RTS_IMPROPER_DOCUMENTATION, PackageStatus.RETURNED_TO_SENDER],
    [RTS_ABANDONMENT, PackageStatus.RETURNED_TO_SENDER],
    [RTS_DUTY_NONPAYMENT, PackageStatus.RETURNED_TO_SENDER],
    [PICKED_UP_AT_CUSTOMS_UNIT, PackageStatus.RETURNED_TO_SENDER],
    [RETURNED_TO_CONSIGNOR, PackageStatus.RETURNED_TO_SENDER],

    [NOTICE_LEFT, PackageStatus.DELIVERY_ATTEMPTED],
    [TEMPORARY_VACATION_HOLD, PackageStatus.DELIVERY_ATTEMPTED],
    [BUSINESS_CLOSED, PackageStatus.DELIVERY_ATTEMPTED],
    [RECEPTACLE_BLOCKED, PackageStatus.DELIVERY_ATTEMPTED],
    [RECEPTACLE_FULL_ITEM_OVERSIZED, PackageStatus.DELIVERY_ATTEMPTED],
    [NO_SECURE_LOCATION_AVAILABLE, PackageStatus.DELIVERY_ATTEMPTED],
    [NO_AUTHORIZED_RECIPIENT_AVAILABLE, PackageStatus.DELIVERY_ATTEMPTED],
    [HAZARDOUS_UNSAFE_DELIVERY_CONDITIONS, PackageStatus.DELIVERY_ATTEMPTED],
    [CLOSED_ON_ARRIVAL, PackageStatus.DELIVERY_ATTEMPTED],
    [CUSTOMER_MOVED, PackageStatus.DELIVERY_ATTEMPTED],
    [ATTEMPTED_DELIVERY_ABROAD, PackageStatus.DELIVERY_ATTEMPTED],
    [NOT_HOME, PackageStatus.DELIVERY_ATTEMPTED],
    [BUSINESS_CLOSED, PackageStatus.DELIVERY_ATTEMPTED],
    [NO_AUTHORIZED_RECIPIENT_AVAILABLE, PackageStatus.DELIVERY_ATTEMPTED],

    [OUT_FOR_DELIVERY_ON_STREET, PackageStatus.OUT_FOR_DELIVERY],
    [ITEM_OUT_FOR_DELIVERY, PackageStatus.OUT_FOR_DELIVERY],
    [OUT_FOR_DELIVERY, PackageStatus.OUT_FOR_DELIVERY],

    [ELECTRONIC_SHIPPING_INFO_RECEIVED, PackageStatus.LABEL_CREATED],
    [PREPARED_FOR_AGENT, PackageStatus.LABEL_CREATED]
]);
